spring:
   main:
      web-application-type: none
      allow-bean-definition-overriding: true
#   cache:
#      type: none
   kafka:
      consumer:
         properties:
            server: 192.168.12.44:9092
            group:
               id: nisbcp-kafka
            topic: hist
logging:
   level:
      net:
         sf:
            ehcache: ERROR
      root: INFO
      org:
         hibernate:
            SQL: ERROR
         springframework:
            data:
               mongodb: WARN
      io:
         siddhi: ERROR

         

################################################################################
#   MARIA       
################################################################################        
---
spring:
   profiles: maria
   autoconfigure:
      exclude: 
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
   jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
      show-sql: false
      properties:
         hibernate:
            format_sql: true
      generate-ddl: true
   datasource:
      url: jdbc:mariadb://192.168.12.24:3306/ncep_service
      driver-class-name: org.mariadb.jdbc.Driver
      username: ncep
      password: ncep!123
      
################################################################################
#   MONGO       
################################################################################        
---
spring:
    profiles: mongo
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    data:
        mongodb:
            host: 192.168.10.185
            port: 20004
            database: tta
            username: tta
            password: tta
      
################################################################################
#   CACHE       
################################################################################
#   Simple
################################################################################         
---
spring:
  profiles: simple
  cache:
      type: simple

################################################################################
#   EHCACHE Configuration
################################################################################         
---
spring:
  profiles: ehcache
  cache:
      type: ehcache
      ehcache:
          config: classpath:ehcache/ehcache-config.xml

################################################################################
#   REDIS Configuration
#   https://docs.spring.io/spring-data/redis/docs/2.1.3.RELEASE/reference/html/
################################################################################         
---
spring:
  profiles: redis
  cache:
      type: redis
      cache-names: element,rule
  redis:
        cluster:
            timeout: 5000
            max-redirects: 3  
            nodes: 192.168.56.101:8001,192.168.56.101:8002,192.168.56.101:8003,192.168.56.101:8004,192.168.56.101:8005,192.168.56.101:8006  